spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.githubcopilot.com
      chat:
        options:
          model: gpt-4o
        completions-path: /chat/completions